### ISSUE TITLE
Adding a screen reader accessible description to ASCII emoji and hiding the ASCII chars from screen reader

### ISSUE THREAD

**Issue by sjarva** [ksylor/ohshitgit#77]
Currently, there's only one ASCII emoji in the repo (¯\_(ツ)_/¯ in the `dude-wheres-my-diff` file), but it would be nice to have in accessible form users who use screen readers, [as it is recommended to do for ASCII art and emojis](https://www.w3.org/TR/WCAG20-TECHS/H86.html).

I'm opening the discussion about as an issue, as is stated in the `CONTRIBUTING.md` file about content changes.

One way to do this could be, for example (this is something that I found on the internet, haven't tested it fully, but will if I can submit a PR to this issue):

````html
File under <span aria-hidden="true">&macr;\\\_(ツ)\_/&macr;</span><span class="sr-only">shrug</span>
````

and then add the `sr-only` class to `site.css`:
````css
.sr-only {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap; /* added line */
      border: 0;
}
````
(Example CSS code from [a11y guidelines](https://a11y-guidelines.orange.com/en/web/components-examples/accessible-hiding/#)
